services:
  traefik:
    image: traefik:v3.6
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./data/certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
  dev-server:
    image: cau777/dev-profile-server
    labels:
      - traefik.http.routers.dev-server-https.rule=Host(`caua-rinaldi.dev`)
      - traefik.http.routers.dev-server-https.tls=true
      - traefik.http.routers.dev-server-https.tls.certresolver=cloudflare
      - traefik.http.routers.dev-server-https.entrypoints=websecure
  sudoku-solver:
    image: cau777/sudoku-solver-server
    labels:
      - traefik.http.routers.sudoku-solver-https.rule=Host(`sudoku.caua-rinaldi.dev`)
      - traefik.http.routers.sudoku-solver-https.tls=true
      - traefik.http.routers.sudoku-solver-https.tls.certresolver=cloudflare
      - traefik.http.routers.sudoku-solver-https.entrypoints=websecure
  regex-designer:
    image: cau777/regex-designer-server
    labels:
      - traefik.http.routers.regex-designer-https.rule=Host(`regex.caua-rinaldi.dev`)
      - traefik.http.routers.regex-designer-https.tls=true
      - traefik.http.routers.regex-designer-https.tls.certresolver=cloudflare
      - traefik.http.routers.regex-designer-https.entrypoints=websecure
  trilium:
    image: triliumnext/notes
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    labels:
      - traefik.http.routers.trilium-http.rule=Host(`notes.caua-rinaldi.dev`)
      - traefik.http.routers.trilium-http.entrypoints=web
      - traefik.http.routers.trilium-https.rule=Host(`notes.caua-rinaldi.dev`)
      - traefik.http.routers.trilium-https.tls=true
      - traefik.http.routers.trilium-https.tls.certresolver=cloudflare
      - traefik.http.routers.trilium-https.entrypoints=websecure
    volumes:
      - ~/data:/home/node/trilium-data
  demo:
    image: nginx:latest
    labels:
      - traefik.http.routers.demo-https.rule=Host(`demo.caua-rinaldi.dev`)
      - traefik.http.routers.demo-https.tls=true
      - traefik.http.routers.demo-https.tls.certresolver=cloudflare
      - traefik.http.routers.demo-https.entrypoints=websecure