api:
  dashboard: true
providers:
  docker: {}
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
log:
  level: DEBUG
certificatesResolvers:
  cloudflare:
    acme:
      email: cauarinaldi451@gmail.com
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
http:
  routers:
    dashboard:
      rule: Host(`admin.caua-rinaldi.dev`)
      service: api@internal
      middlewares:
        - auth
      tls:
        certresolver: cloudflare
      entrypoints:
        - web
        - websecure
  middlewares:
    auth:
      basicAuth:
        users:
          - "cau777:$apr1$RxsmiBqp$Pme/fcoxf5lei95vJ2bwL0"
